"""State schemas for the RAG query LangGraph.

Defines the TypedDicts used as graph state plus the public input and output
types exposed to the parent orchestrator.
"""

from __future__ import annotations

from typing import Any, TypedDict

from latam_investment_research_agent.agents.analytics.constants import DEFAULT_EXPORT_ROW_LIMIT
from latam_investment_research_agent.agents.analytics.models.domain import TableSchema


class RAGQueryState(TypedDict, total=False):
    """Mutable state passed between nodes of the RAG query LangGraph.

    Attributes:
        natural_language_question: The question received from the parent orchestrator.
        export_row_limit: Maximum rows to include in the CSV export.
        export_directory: Directory where CSV files are written.
        available_table_schemas: All tables and columns retrieved from ClickHouse.
        selected_table_names: Table names the LLM selected as relevant.
        assembled_sql_queries: SQL queries generated by the LLM.
        query_result_records: Rows returned by executing all queries.
        was_truncated: True if results were truncated to ``export_row_limit``.
        export_file_path: Absolute path to the written CSV file.  ``None`` if
            no relevant data was found.
        rationale: LLM explanation of why the data answers the question.
        rag_query_output: Final compiled output populated by the terminal node.
        error: Set if a fatal error halts the graph.
    """

    natural_language_question: str
    export_row_limit: int
    export_directory: str
    available_table_schemas: list[TableSchema]
    selected_table_names: list[str]
    assembled_sql_queries: list[str]
    query_result_records: list[dict[str, Any]]
    was_truncated: bool
    export_file_path: str | None
    rationale: str | None
    rag_query_output: RAGQueryOutput
    error: str | None


class RAGQueryInput(TypedDict, total=False):
    """Public input supplied by the parent orchestrator to the RAG query graph.

    Attributes:
        natural_language_question: The question to answer from ClickHouse data.
        export_row_limit: Maximum rows in the CSV export.  Defaults to
            ``DEFAULT_EXPORT_ROW_LIMIT``.
        export_directory: Directory where the CSV file is written.
    """

    natural_language_question: str
    export_row_limit: int
    export_directory: str


class RAGQueryOutput(TypedDict):
    """Structured output returned by the RAG query graph to the caller.

    Attributes:
        export_file_path: Absolute path to the exported CSV file.
        rationale: Human-readable explanation of why this data answers the question.
            Includes a truncation note when ``was_truncated`` is ``True``.
        sql_queries_used: The exact SQL queries that were executed.
        row_count: Number of rows in the exported CSV.
        was_truncated: ``True`` if results were truncated to ``export_row_limit``.
    """

    export_file_path: str | None
    rationale: str
    sql_queries_used: list[str]
    row_count: int
    was_truncated: bool


DEFAULT_RAG_QUERY_INPUT: dict[str, int | str] = {
    "export_row_limit": DEFAULT_EXPORT_ROW_LIMIT,
    "export_directory": "./exports",
}
"""Default values merged with caller-supplied RAGQueryInput fields."""
